<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * MarsupilamiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarsupilamiRepository extends \Doctrine\ORM\EntityRepository {

    public function friends($id) {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('u,a')
                        ->from('AppBundle:Marsupilami', 'u')
                        ->leftJoin('u.friends', 'a')
                        ->where('u.id = :id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->getOneOrNullResult(Query::HYDRATE_ARRAY);
    }

    public function users() {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('u')
                        ->from('AppBundle:Marsupilami', 'u')
                        ->getQuery()
                        ->getResult(Query::HYDRATE_ARRAY);
    }
    
    public function search($keyword) {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('u')
                        ->from('AppBundle:Marsupilami', 'u')
                        ->where("u.username LIKE :keyword ")//OR u.race LIKE :keyword OR u.famille LIKE :keyword")
                        ->setParameter('keyword', '%' . $keyword . '%') 
                        ->orderBy('u.username', 'DESC')
                        ->getQuery()
                        ->getResult(Query::HYDRATE_ARRAY);
    }

}
